name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout kode
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Prijava v Docker Hub (samo enkrat!)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3️⃣ Zgradi Docker sliko
    - name: Build Docker Image
      run: |
        IMAGE_NAME=cernjak/videoigre
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$COMMIT_SHA .

    # 4️⃣ Push Docker sliko
    - name: Push Docker Image
      run: |
        IMAGE_NAME=cernjak/videoigre
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$COMMIT_SHA